### ISSUE TITLE
PyDS/pyds/ingestion.py

### ISSUE THREAD

**Issue by emanuel-sygal** [talperetz/pyds#2]
I Can't run a script and check this, but it seems that in the function
infer_columns_statistical_types
we don't want to define id_cols that way (it checks if all values are distinct, and it returns the rows)

Also is_supervised looks unused, and (target_column in test_df.columns) looks like it should be  (train_df.columns == test_df.columns), and the line
(target_column not in train_df.columns) or (len(train_df[target_column].index) == 0)
 is interesting: why need the second condition? (it runs after the validate of >50 rows)

infer_columns_statistical_types mistakenly classifies platform codes etc. as numeric types. Suggestion: look at floats as numeric types and enable manually inserting a list of int columns that are numeric (I think there are usually more integer-codes than integer-numeric variables)

**Comment by talperetz** [comment]
thanks for the review - I added the ability to manually set columns types, not tested yet
if you clone it now, and pip install all the dependencies it would work and then you could check it for yourself
in the future I would like to separate numerical, categorical (there's a categorical type in pandas !) and text
and then add some general NLP approaches (BOW, stemming, lemmatization etc)
